# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


import os
import subprocess
import glob
import pandas as pd
from snakemake.utils import validate

# enforce bash
shell.executable("/bin/bash")


# reference the config file
configfile: "config/config.yaml"

#rule all:
    #input:
        ## The first rule should define the default target files
        ## Subsequent target rules can be specified below. They should start with all_*.


# including individual rules
include: "rules/shapeit4.smk"
