$schema: "http://json-schema.org/draft-07/schema#"
description: "54gene-phasing-pipeline/snakemake analysis configuration file"
type: object
properties:
  manifest:
    type: string
  genome_build:
    type: string
    pattern: "^b37$|^b38$|^t2t$"
  tools:
    type: object
    pattern: "^shapeit4$|^beagle$|^eagle$|^shapeit5$"
    properties:
      shapeit4:
        type: object
        properties:
          enabled:
            type: boolean
          mcmc-iterations:
            type: string
            pattern: "[0-9]+[b|p|m],"
          pbwt-depth:
            type: integer
            minimum: 2
          pbwt-mdr:
            type: number
            minimum: 0.0
          pbwt-mac:
            type: integer
            minimum: 2
          seed:
            type: integer
            minimum: 1
          sequencing:
            type: boolean
        required:
          - enabled
          - mcmc-iterations
          - pbwt-depth
          - pbwt-mdr
          - pbwt-mac
          - seed
          - sequencing
      shapeit5:
        type: object
        properties:
          enabled:
            type: boolean
          mcmc-iterations:
            type: string
            pattern: "[0-9]+[b|p|m],"
          pbwt-depth:
            type: integer
            minimum: 2
          pbwt-mdr:
            type: number
            minimum: 0.0
          pbwt-mac:
            type: integer
            minimum: 2
          seed:
            type: integer
            minimum: 1
          sequencing:
            type: boolean
        required:
          - enabled
          - mcmc-iterations
          - pbwt-depth
          - pbwt-mdr
          - pbwt-mac
          - seed
          - sequencing
      eagle:
        type: object
        properties:
          enabled:
            type: boolean
          kpbwt:
            type: integer
            minimum: 2
          pbwt-iters:
            type: integer
            minimum: 0
          expect-ibd:
            type: number
            minimum: 0
          no-impute-missing:
            type: boolean
          geno-err-prob:
            type: number
            minimum: 0.00001
            maximum: 0.5
          hist-factor:
            type: number
            minimum: 0
        required:
          - enabled
          - kpbwt
          - pbwt-iters
          - expect-ibd
          - no-impute-missing
          - geno-err-prob
          - hist-factor
      beagle:
        type: object
        properties:
          enabled:
            type: boolean
          seed:
            type: number
            minimum: 1
          burnin:
            type: number
            minimum: 3
          iterations:
            type: number
            minimum: 12
        required:
          - enabled
          - seed 
          - burnin
          - iterations
    required:
      - shapeit4
      - eagle
      - beagle
  evaluation:
    type: object
    properties:
      enabled:
        type: boolean
        default: no
      fam:
        type: string
      maf:
        type: number
        minimum: 0.0
        maximum: 0.5
    required:
      - enabled
      - fam
      - maf
  reference_panel:
    type: string
    default: ""
  recombination_maps:
    type: string
    default: ""
required:
  - evaluation
  - genome_build
  - evaluation
