$schema: "http://json-schema.org/draft-07/schema#"
description: "54gene-phasing-pipeline/snakemake global configuration file"
type: object
properties:
  manifest:
    type: string
required:
  - manifest
